#!/usr/bin/env bash
# tests/guard_smoke.sh — single-writer mount-guard smoke on a REAL fabric target
# ==============================================================================
#
# The S1 scoping rig's guard-smoke, productized (docs/design-nvmeof-target-
# management.md §6.8 / G4): runs the writer-guard matrix against namespaces
# **shared by the product's own verbs** (the fidelity substrate,
# tests/nvmeof_target_substrate.sh) on the kernel nvmet target — THE target
# since SPDK was retired (R-SYM-8, docs/design-symmetric-metadata.md
# §5.8.1; the SPDK arm and its PTPL power-cycle leg left with it). Supersedes
# the scoping rig's guard-smoke (removed from the tree — history:
# `.agents/spdk-scoping/guard-smoke.sh` at c615e3a).
#
# Family sibling: tests/mw_two_registrants_leg.sh — the rung-2 per-mount
# host-identity leg (design-full-multi-writer KD-MW-3/§5.2): two PR
# registrants from ONE box via the product connect path
# (`nvmeof connect --hostnqn/--hostid`) on nvmet-tcp (resv_enable=1),
# preempt one, assert the DEVICE rejects the preempted holder.
#
# Usage
#   sudo tests/guard_smoke.sh [--stack nvmet] [--loops N]
#
#   --stack   the target stack (nvmet is the only admissible value; the
#             retired spdk refuses loud, naming nvmet)
#   --loops   kill-9 -> remount cycles (default 1; the nightly matrix runs 10
#             — the multi-run discipline applies: a fix restarts the count)
#
# Legs (each asserted; exits nonzero on any FAIL):
#   0.  scrub: kill stale daemons, drain PR residue, wipe superblocks
#   0b. Register-semantics probe (spec-strict vs lenient — PROBED, never
#       assumed; kernel nvmet measured spec-strict 2026-07-17)
#   1.  format --single-writer (the guard's ONE-writer class since the PR-14
#       flip; a default-class set JOINS a second RW mount instead) + mount
#       --daemon, writer_guard_mode == flock+pr
#   2.  double-mount refusal while the first daemon serves
#   3.  claim clear refused while live-mounted
#   4.  kill -9 -> remount recovery x LOOPS (md5 data integrity per cycle);
#       the S1 register ladder asserted against the probed semantics
#   6.  clean unmount + claim clear no-op + zero PR residue
#
# (Reservation persistence across a TARGET restart is nvmet's G2 leg in
# tests/run_nvmeof_fidelity.sh: configfs wipe -> `nvmeof restore` -> the
# holder reattaches; nvmet has no PTPL, so pr_reacquires growth there is
# expected — the heartbeat re-check law covers it.)
#
# Requires: root, a healthy fidelity substrate (tests/nvmeof_target_substrate.sh
# create), nvme-cli, jq. Output transcript: $FIDELI_STATE/guard-smoke-nvmet.txt

set -uo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
STATE="${FIDELI_STATE:-/tmp/squeezefs-fideli}"

ARM=nvmet
LOOPS=1
while [ $# -gt 0 ]; do
    case "$1" in
    --stack)
        ARM="${2:?--stack needs nvmet}"
        # The grammar rung, before sudo and before any substrate is read
        # (the binary's own rule for the same refusal).
        case "$ARM" in
        nvmet) ;;
        spdk)
            echo "--stack spdk: SPDK was RETIRED as an NVMe-oF target (R-SYM-8) — the kernel nvmet target is THE target; run with --stack nvmet (the default)" >&2
            exit 2
            ;;
        *)
            echo "--stack must be nvmet (the one supported target), got '$ARM'" >&2
            exit 2
            ;;
        esac
        shift 2
        ;;
    --loops)
        LOOPS="${2:?--loops needs a count}"
        shift 2
        ;;
    -h | --help)
        awk 'NR > 1 && /^#/ { sub(/^# ?/, ""); print; next } NR > 1 { exit }' "$0"
        exit 0
        ;;
    *)
        echo "unknown argument '$1' (see --help)" >&2
        exit 2
        ;;
    esac
done

if [ "$(id -u)" -ne 0 ]; then
    # Re-exec via sudo with the parsed arguments rebuilt as an array (never
    # word-split command substitution) and the fidelity env forwarded.
    REEXEC=(--stack "$ARM" --loops "$LOOPS")
    exec sudo env FIDELI_STATE="$STATE" bash "$0" "${REEXEC[@]}"
fi

if [ ! -f "$STATE/env.sh" ]; then
    echo "no fidelity substrate at $STATE — run: sudo $REPO/tests/nvmeof_target_substrate.sh create" >&2
    exit 2
fi
# shellcheck disable=SC1091 # generated by nvmeof_target_substrate.sh create
. "$STATE/env.sh"
# shellcheck disable=SC1091 # generated by nvmeof_target_substrate.sh create
. "$STATE/devices.env"
SQZ="$FIDELI_BIN"

# ARM was validated at the parser; only the NQN wiring remains.
NQN_META="$NQN_GMETA_NVMET"
NQN_DATA="$NQN_GDATA_NVMET"

OUT="$STATE/guard-smoke-$ARM.txt"
DLOG="$STATE/guard-daemon-$ARM.log"
MNT="$STATE/mnt-guard-$ARM"
MNT2="$STATE/mnt-guard-$ARM-2"

# Devices re-resolved by NQN at start — controller numbering can shift as
# other fidelity legs connect/disconnect their own subsystems.
finddev() { # nqn -> /dev/nvmeXn1
    local nqn=$1 c cname
    for _ in $(seq 1 60); do
        for c in /sys/class/nvme/nvme*; do
            [ -e "$c/subsysnqn" ] || continue
            if [ "$(cat "$c/subsysnqn" 2>/dev/null)" = "$nqn" ]; then
                cname=$(basename "$c")
                if [ -b "/dev/${cname}n1" ]; then
                    echo "/dev/${cname}n1"
                    return 0
                fi
            fi
        done
        sleep 0.5
    done
    return 1
}
META=$(finddev "$NQN_META") || { echo "no initiator device for $NQN_META" >&2; exit 2; }
DATA=$(finddev "$NQN_DATA") || { echo "no initiator device for $NQN_DATA" >&2; exit 2; }

FAILS=0
log()  { echo "[guard-$ARM] $*" | tee -a "$OUT"; }
pass() { log "PASS: $*"; }
fail() {
    log "FAIL: $*"
    FAILS=$((FAILS + 1))
}
run() {
    echo "\$ $*" >> "$OUT"
    "$@" >> "$OUT" 2>&1
    local rc=$?
    echo "(rc=$rc)" >> "$OUT"
    return $rc
}
is_mounted() { awk -v m="$MNT" '$2==m{f=1} END{exit !f}' /proc/mounts; }
daemon_pid() { pgrep -f "squeezefs.*mount sqmeta://$META $MNT " | head -1; }
mount_it() {
    # Drain the udev queue first: our own wipe/format write-then-close fires
    # a `change` uevent, and systemd-udevd holds a BSD flock on the block
    # node while re-probing it (systemd BLOCK_DEVICE_LOCKING) — colliding
    # with the guard's Layer-A LOCK_EX|LOCK_NB. The guard now waits such
    # claim-less transient holders out bounded (the anonymous-holder arm),
    # so this settle is determinism polish, not correctness: it keeps the
    # matrix's timing rows from absorbing a ~ms wait-out. Settling is causal
    # (never a retry that could mask a REAL double-mount refusal).
    udevadm settle --timeout=10 2>/dev/null || true
    RUST_LOG=info run "$SQZ" --log-file "$DLOG" mount "sqmeta://$META" "$MNT" --daemon --allow-other
}
wait_mounted() {
    local i
    for i in $(seq 1 60); do
        is_mounted && return 0
        sleep 0.5
    done
    return 1
}
stat_field() { # field -> first scalar off the .stats inode
    jq -r ".metrics.$1[0] // .metrics.$1 // .$1[0] // .$1 // empty" "$MNT/.stats" 2>/dev/null
}

: > "$OUT"
: > "$DLOG"
mkdir -p "$MNT" "$MNT2"
log "arm=$ARM meta=$META ($NQN_META) data=$DATA loops=$LOOPS $(date -Is)"
log "binary: $SQZ ($(md5sum "$SQZ" | cut -d' ' -f1))"

log "0. scrub: kill stale daemons, unmount, drain PR residue, wipe superblocks"
pkill -f "squeezefs.*mount sqmeta://$META" && sleep 2
umount "$MNT" 2>/dev/null
umount -l "$MNT" 2>/dev/null
sleep 1
# PR scrub: unregister every key this HOST holds (fidelity namespaces only
# ever see this host, so this drains prior-session residue to regctl=0).
for k in $(nvme resv-report "$META" --eds -o json 2>/dev/null | jq -r '.regctlext[]?.rkey'); do
    run nvme resv-register "$META" --crkey="$k" --rrega=1
done
run dd if=/dev/zero of="$META" bs=1M count=16 oflag=direct
run dd if=/dev/zero of="$DATA" bs=1M count=16 oflag=direct

log "0b. Register-semantics probe (stale different-key register, the guard's shape)"
run nvme resv-register "$META" --nrkey=0xA11CE --rrega=0 --iekey --cptpl=3
if run nvme resv-register "$META" --nrkey=0xB0B --rrega=0 --iekey --cptpl=3; then
    SEMANTICS=lenient
    run nvme resv-register "$META" --crkey=0xB0B --rrega=1
else
    SEMANTICS=strict
    run nvme resv-register "$META" --crkey=0xA11CE --rrega=1
fi
run nvme resv-register "$META" --crkey=0xA11CE --rrega=1
log "register semantics: $SEMANTICS"

# `--single-writer`: this rig's SUBJECT is the D0 single-writer mount
# guard (leg 2's double-mount refusal, leg 3's live claim). Since the PR-14
# default flip a plain `format` stamps the symmetric forest, on which a
# second RW mount of the set JOINS the manager as a writer (the join
# ladder — the fidelity tier's `sym-join-ladder` leg pins that law); the
# ONE-writer posture the guard refuses a second writer under is the
# `--single-writer` class's (design-symmetric-metadata §7.3).
log "1. format --single-writer + mount (cache-less)"
run "$SQZ" format "sqmeta://$META" "sqdata://$DATA" --force --single-writer || { fail "format"; exit 1; }
mount_it
wait_mounted || { fail "initial mount did not appear"; exit 1; }
sleep 2
MODE=$(stat_field writer_guard_mode)
if [ "$MODE" = "flock+pr" ]; then
    pass "writer_guard_mode=flock+pr (enforcement grade)"
else
    fail "writer_guard_mode=$MODE (want flock+pr)"
fi
run dd if=/dev/urandom of="$MNT/smoke.bin" bs=1M count=8
run sync
MD5=$(md5sum "$MNT/smoke.bin" | cut -d' ' -f1)
log "smoke.bin md5=$MD5"

log "2. double-mount refusal while first daemon serves"
if run "$SQZ" mount "sqmeta://$META" "$MNT2" --daemon --allow-other; then
    fail "second concurrent mount was NOT refused"
    umount "$MNT2" 2>/dev/null
else
    if grep -q "single-writer\|writer lock\|claimed by a live writer" "$OUT"; then
        pass "double-mount refused naming the guard"
    else
        pass "double-mount refused (rc!=0)"
    fi
fi

log "3. claim clear refused while live-mounted"
if run "$SQZ" claim clear "sqmeta://$META"; then
    fail "claim clear succeeded against a LIVE mount"
else
    pass "claim clear refused while live"
fi

for i in $(seq 1 "$LOOPS"); do
    log "4.$i kill -9 -> remount (cycle $i/$LOOPS)"
    DPID=$(daemon_pid)
    [ -n "$DPID" ] || { fail "no daemon pid at cycle $i"; break; }
    kill -9 "$DPID"
    sleep 2
    umount -l "$MNT" 2>/dev/null
    sleep 1
    mount_it
    if wait_mounted; then
        sleep 2
        MODE2=$(stat_field writer_guard_mode)
        MD5B=$(md5sum "$MNT/smoke.bin" 2>/dev/null | cut -d' ' -f1)
        [ "$MODE2" = "flock+pr" ] || fail "cycle $i: remount mode=$MODE2 (want flock+pr)"
        [ "$MD5B" = "$MD5" ] || fail "cycle $i: data integrity ($MD5B != $MD5)"
        if [ "$MODE2" = "flock+pr" ] && [ "$MD5B" = "$MD5" ]; then
            pass "cycle $i: kill-9 -> remount recovered (flock+pr, data intact)"
        fi
    else
        fail "cycle $i: REMOUNT did not appear after kill -9"
        # capture the refusal verbatim (the daemon parent surfaces the
        # child's bootstrap error on its own stderr)
        run timeout 30 "$SQZ" mount "sqmeta://$META" "$MNT" --daemon --allow-other
        break
    fi
done

LADDER_HITS=$(grep -c "register conflicted with our own stale" "$DLOG" 2>/dev/null || true)
if [ "$SEMANTICS" = "strict" ]; then
    if [ "${LADDER_HITS:-0}" -ge 1 ]; then
        pass "register ladder fired on the strict target (log hits=$LADDER_HITS)"
    else
        fail "register ladder never fired on a strict target (expected per probe)"
    fi
else
    if [ "${LADDER_HITS:-0}" -eq 0 ]; then
        pass "register ladder did NOT fire on the lenient target (fast path)"
    else
        fail "register ladder fired on a lenient target (hits=$LADDER_HITS) — divergence"
    fi
fi

log "6. clean unmount + claim clear no-op + zero PR residue"
run umount "$MNT"
sleep 1
# kill-9'd daemons orphan client heartbeat records; claim clear REFUSES
# while any looks live (one staleness law, TTL 45 s) — prove the refusal,
# wait out the TTL, then prove the no-op.
if ! run "$SQZ" claim clear "sqmeta://$META"; then
    if grep -q "live client registrations" "$OUT"; then
        pass "claim clear refused under TTL-fresh crash-orphaned client records"
    else
        fail "claim clear errored for an unexpected reason"
    fi
    log "waiting out the 45 s client TTL before the no-op check"
    sleep 50
    run "$SQZ" claim clear "sqmeta://$META" || fail "claim clear still refused after TTL"
fi
if grep -q "no writer claim present" "$OUT"; then
    pass "claim clear after clean unmount: no-op (claim deleted at unmount)"
else
    fail "claim clear did not report the no-op"
fi
REG=$(nvme resv-report "$META" --eds -o json 2>/dev/null | jq -r .regctl)
if [ "${REG:-x}" = "0" ]; then
    pass "zero PR residue after clean unmount (regctl=0)"
else
    fail "PR residue after clean unmount (regctl=$REG)"
fi

log "verdict: $FAILS failure(s)"
exit $((FAILS > 0 ? 1 : 0))
