#!/usr/bin/env bash
# tests/guard_smoke.sh — single-writer mount-guard smoke on a REAL fabric stack
# =============================================================================
#
# The S1 scoping rig's guard-smoke, productized (docs/design-nvmeof-target-
# management.md §6.8 / G4): runs the writer-guard matrix against namespaces
# **shared by the product's own verbs** (the fidelity substrate,
# tests/nvmeof_target_substrate.sh), on either target stack. Supersedes
# `.agents/spdk-scoping/guard-smoke.sh` (kept there as evidence lineage).
#
# Usage
#   sudo tests/guard_smoke.sh [--stack spdk|nvmet] [--loops N] [--ptpl]
#
#   --stack   which target stack's guard namespaces to ride (default spdk)
#   --loops   kill-9 -> remount cycles (default 1; the nightly matrix runs 10
#             — the multi-run discipline applies: a fix restarts the count)
#   --ptpl    (spdk only) add the target power-cycle leg: SIGKILL spdk_tgt by
#             OUR pidfile -> product `nvmeof target start` (load_config) =>
#             the live holder rides it out (fenced=0, pr_reacquires=0 — the
#             §6.7 PTPL signal), then a post-cycle kill-9 remount
#
# Legs (each asserted; exits nonzero on any FAIL):
#   0.  scrub: kill stale daemons, drain PR residue, wipe superblocks
#   0b. Register-semantics probe (spec-strict vs lenient — PROBED, never
#       assumed per stack; both stacks measured spec-strict 2026-07-17)
#   1.  format + mount --daemon, writer_guard_mode == flock+pr
#   2.  double-mount refusal while the first daemon serves
#   3.  claim clear refused while live-mounted
#   4.  kill -9 -> remount recovery x LOOPS (md5 data integrity per cycle);
#       the S1 register ladder asserted against the probed semantics
#   5.  (--ptpl) target power cycle while the holder is ALIVE (product-verb
#       restart), then kill-9 remount against the ptpl-restored state
#   6.  clean unmount + claim clear no-op + zero PR residue
#
# Requires: root, a healthy fidelity substrate (tests/nvmeof_target_substrate.sh
# create), nvme-cli, jq. Output transcript: $FIDELI_STATE/guard-smoke-<stack>.txt

set -uo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
STATE="${FIDELI_STATE:-/tmp/squeezefs-fideli}"

ARM=spdk
LOOPS=1
PTPL=0
while [ $# -gt 0 ]; do
    case "$1" in
    --stack)
        ARM="${2:?--stack needs spdk|nvmet}"
        shift 2
        ;;
    --loops)
        LOOPS="${2:?--loops needs a count}"
        shift 2
        ;;
    --ptpl)
        PTPL=1
        shift
        ;;
    -h | --help)
        awk 'NR > 1 && /^#/ { sub(/^# ?/, ""); print; next } NR > 1 { exit }' "$0"
        exit 0
        ;;
    *)
        echo "unknown argument '$1' (see --help)" >&2
        exit 2
        ;;
    esac
done

if [ "$(id -u)" -ne 0 ]; then
    # Re-exec via sudo with the parsed arguments rebuilt as an array (never
    # word-split command substitution) and the fidelity env forwarded.
    REEXEC=(--stack "$ARM" --loops "$LOOPS")
    [ "$PTPL" = 1 ] && REEXEC+=(--ptpl)
    exec sudo env FIDELI_STATE="$STATE" bash "$0" "${REEXEC[@]}"
fi

if [ ! -f "$STATE/env.sh" ]; then
    echo "no fidelity substrate at $STATE — run: sudo $REPO/tests/nvmeof_target_substrate.sh create" >&2
    exit 2
fi
# shellcheck disable=SC1091 # generated by nvmeof_target_substrate.sh create
. "$STATE/env.sh"
# shellcheck disable=SC1091 # generated by nvmeof_target_substrate.sh create
. "$STATE/devices.env"
SQZ="$FIDELI_BIN"
RUN_DIR="$SQUEEZEFS_NVMEOF_RUN_DIR"

case "$ARM" in
spdk)
    NQN_META="$NQN_GMETA_SPDK"
    NQN_DATA="$NQN_GDATA_SPDK"
    ;;
nvmet)
    NQN_META="$NQN_GMETA_NVMET"
    NQN_DATA="$NQN_GDATA_NVMET"
    ;;
*)
    echo "--stack must be spdk|nvmet" >&2
    exit 2
    ;;
esac
if [ "$PTPL" = 1 ] && [ "$ARM" != spdk ]; then
    echo "--ptpl is spdk-only (kernel nvmet has ptpls=0 — reservations do not survive target restarts there by design)" >&2
    exit 2
fi

OUT="$STATE/guard-smoke-$ARM.txt"
DLOG="$STATE/guard-daemon-$ARM.log"
MNT="$STATE/mnt-guard-$ARM"
MNT2="$STATE/mnt-guard-$ARM-2"

# Devices re-resolved by NQN at start — controller numbering can shift as
# other fidelity legs connect/disconnect their own subsystems.
finddev() { # nqn -> /dev/nvmeXn1
    local nqn=$1 c cname
    for _ in $(seq 1 60); do
        for c in /sys/class/nvme/nvme*; do
            [ -e "$c/subsysnqn" ] || continue
            if [ "$(cat "$c/subsysnqn" 2>/dev/null)" = "$nqn" ]; then
                cname=$(basename "$c")
                if [ -b "/dev/${cname}n1" ]; then
                    echo "/dev/${cname}n1"
                    return 0
                fi
            fi
        done
        sleep 0.5
    done
    return 1
}
META=$(finddev "$NQN_META") || { echo "no initiator device for $NQN_META" >&2; exit 2; }
DATA=$(finddev "$NQN_DATA") || { echo "no initiator device for $NQN_DATA" >&2; exit 2; }

FAILS=0
log()  { echo "[guard-$ARM] $*" | tee -a "$OUT"; }
pass() { log "PASS: $*"; }
fail() {
    log "FAIL: $*"
    FAILS=$((FAILS + 1))
}
run() {
    echo "\$ $*" >> "$OUT"
    "$@" >> "$OUT" 2>&1
    local rc=$?
    echo "(rc=$rc)" >> "$OUT"
    return $rc
}
is_mounted() { awk -v m="$MNT" '$2==m{f=1} END{exit !f}' /proc/mounts; }
daemon_pid() { pgrep -f "squeezefs.*mount sqmeta://$META" | head -1; }
mount_it() {
    # Drain the udev queue first: our own wipe/format write-then-close fires
    # a `change` uevent, and systemd-udevd holds a BSD flock on the block
    # node while re-probing it (systemd BLOCK_DEVICE_LOCKING) — colliding
    # with the guard's Layer-A LOCK_EX|LOCK_NB and refusing the mount as
    # "another squeezefs process holds the writer lock". Settling is causal
    # (never a retry that could mask a REAL double-mount refusal).
    udevadm settle --timeout=10 2>/dev/null || true
    RUST_LOG=info run "$SQZ" --log-file "$DLOG" mount "sqmeta://$META" "$MNT" --daemon --allow-other
}
wait_mounted() {
    local i
    for i in $(seq 1 60); do
        is_mounted && return 0
        sleep 0.5
    done
    return 1
}
stat_field() { # field -> first scalar off the .stats inode
    jq -r ".metrics.$1[0] // .metrics.$1 // .$1[0] // .$1 // empty" "$MNT/.stats" 2>/dev/null
}

: > "$OUT"
: > "$DLOG"
mkdir -p "$MNT" "$MNT2"
log "arm=$ARM meta=$META ($NQN_META) data=$DATA loops=$LOOPS ptpl=$PTPL $(date -Is)"
log "binary: $SQZ ($(md5sum "$SQZ" | cut -d' ' -f1))"

log "0. scrub: kill stale daemons, unmount, drain PR residue, wipe superblocks"
pkill -f "squeezefs.*mount sqmeta://$META" && sleep 2
umount "$MNT" 2>/dev/null
umount -l "$MNT" 2>/dev/null
sleep 1
# PR scrub: unregister every key this HOST holds (fidelity namespaces only
# ever see this host, so this drains prior-session residue to regctl=0).
for k in $(nvme resv-report "$META" --eds -o json 2>/dev/null | jq -r '.regctlext[]?.rkey'); do
    run nvme resv-register "$META" --crkey="$k" --rrega=1
done
run dd if=/dev/zero of="$META" bs=1M count=16 oflag=direct
run dd if=/dev/zero of="$DATA" bs=1M count=16 oflag=direct

log "0b. Register-semantics probe (stale different-key register, the guard's shape)"
run nvme resv-register "$META" --nrkey=0xA11CE --rrega=0 --iekey --cptpl=3
if run nvme resv-register "$META" --nrkey=0xB0B --rrega=0 --iekey --cptpl=3; then
    SEMANTICS=lenient
    run nvme resv-register "$META" --crkey=0xB0B --rrega=1
else
    SEMANTICS=strict
    run nvme resv-register "$META" --crkey=0xA11CE --rrega=1
fi
run nvme resv-register "$META" --crkey=0xA11CE --rrega=1
log "register semantics: $SEMANTICS"

log "1. format + mount (cache-less)"
run "$SQZ" format "sqmeta://$META" "sqdata://$DATA" --force || { fail "format"; exit 1; }
mount_it
wait_mounted || { fail "initial mount did not appear"; exit 1; }
sleep 2
MODE=$(stat_field writer_guard_mode)
if [ "$MODE" = "flock+pr" ]; then
    pass "writer_guard_mode=flock+pr (enforcement grade)"
else
    fail "writer_guard_mode=$MODE (want flock+pr)"
fi
run dd if=/dev/urandom of="$MNT/smoke.bin" bs=1M count=8
run sync
MD5=$(md5sum "$MNT/smoke.bin" | cut -d' ' -f1)
log "smoke.bin md5=$MD5"

log "2. double-mount refusal while first daemon serves"
if run "$SQZ" mount "sqmeta://$META" "$MNT2" --daemon --allow-other; then
    fail "second concurrent mount was NOT refused"
    umount "$MNT2" 2>/dev/null
else
    if grep -q "single-writer\|writer lock\|claimed by a live writer" "$OUT"; then
        pass "double-mount refused naming the guard"
    else
        pass "double-mount refused (rc!=0)"
    fi
fi

log "3. claim clear refused while live-mounted"
if run "$SQZ" claim clear "sqmeta://$META"; then
    fail "claim clear succeeded against a LIVE mount"
else
    pass "claim clear refused while live"
fi

for i in $(seq 1 "$LOOPS"); do
    log "4.$i kill -9 -> remount (cycle $i/$LOOPS)"
    DPID=$(daemon_pid)
    [ -n "$DPID" ] || { fail "no daemon pid at cycle $i"; break; }
    kill -9 "$DPID"
    sleep 2
    umount -l "$MNT" 2>/dev/null
    sleep 1
    mount_it
    if wait_mounted; then
        sleep 2
        MODE2=$(stat_field writer_guard_mode)
        MD5B=$(md5sum "$MNT/smoke.bin" 2>/dev/null | cut -d' ' -f1)
        [ "$MODE2" = "flock+pr" ] || fail "cycle $i: remount mode=$MODE2 (want flock+pr)"
        [ "$MD5B" = "$MD5" ] || fail "cycle $i: data integrity ($MD5B != $MD5)"
        if [ "$MODE2" = "flock+pr" ] && [ "$MD5B" = "$MD5" ]; then
            pass "cycle $i: kill-9 -> remount recovered (flock+pr, data intact)"
        fi
    else
        fail "cycle $i: REMOUNT did not appear after kill -9"
        # capture the refusal verbatim (the daemon parent surfaces the
        # child's bootstrap error on its own stderr)
        run timeout 30 "$SQZ" mount "sqmeta://$META" "$MNT" --daemon --allow-other
        break
    fi
done

LADDER_HITS=$(grep -c "register conflicted with our own stale" "$DLOG" 2>/dev/null || true)
if [ "$SEMANTICS" = "strict" ]; then
    if [ "${LADDER_HITS:-0}" -ge 1 ]; then
        pass "register ladder fired on the strict target (log hits=$LADDER_HITS)"
    else
        fail "register ladder never fired on a strict target (expected per probe)"
    fi
else
    if [ "${LADDER_HITS:-0}" -eq 0 ]; then
        pass "register ladder did NOT fire on the lenient target (fast path)"
    else
        fail "register ladder fired on a lenient target (hits=$LADDER_HITS) — divergence"
    fi
fi

if [ "$PTPL" = 1 ]; then
    log "5. PTPL: target power cycle while holder ALIVE — PRODUCT verbs (SIGKILL by our pidfile -> 'nvmeof target start' replays tgt-config via load_config)"
    SPID=$(cat "$RUN_DIR/spdk_tgt.pid" 2>/dev/null)
    if [ -z "${SPID:-}" ]; then
        fail "no spdk_tgt pidfile at $RUN_DIR — substrate not in pidfile mode?"
    else
        kill -9 "$SPID" 2>/dev/null
        log "spdk_tgt killed (pid $SPID — simulated target power loss)"
        sleep 1
        if run "$SQZ" nvmeof target start; then
            if grep -q "load_config applied" "$OUT"; then
                pass "product 'target start' replayed the SPDK source of truth (load_config)"
            else
                fail "target start ran but no load_config line"
            fi
        else
            fail "product 'target start' after SIGKILL"
        fi
        OK=""
        for i in $(seq 1 60); do
            dd if="$MNT/smoke.bin" of=/dev/null bs=1M count=1 2>/dev/null && { OK=1; break; }
            sleep 2
        done
        sleep 12 # one heartbeat re-check past reattach
        FENCED=$(stat_field writer_guard_fenced)
        REACQ=$(stat_field writer_guard_pr_reacquires)
        MD5C=$(md5sum "$MNT/smoke.bin" 2>/dev/null | cut -d' ' -f1)
        if [ -n "$OK" ] && [ "$MD5C" = "$MD5" ] && [ "${FENCED:-1}" = "0" ] && [ "${REACQ:-1}" = "0" ]; then
            pass "holder rode out the power cycle (PTPL: fenced=0, pr_reacquires=0, data intact)"
        else
            fail "holder did not ride out the power cycle (io=${OK:-no} md5=$MD5C fenced=$FENCED reacq=$REACQ)"
        fi
        log "5b. kill -9 AFTER the power cycle -> remount (ladder against ptpl-restored state)"
        DPID=$(daemon_pid)
        [ -n "$DPID" ] && kill -9 "$DPID"
        sleep 2
        umount -l "$MNT" 2>/dev/null
        sleep 1
        mount_it
        if wait_mounted; then
            sleep 2
            MD5D=$(md5sum "$MNT/smoke.bin" 2>/dev/null | cut -d' ' -f1)
            if [ "$MD5D" = "$MD5" ]; then
                pass "post-power-cycle kill-9 remount recovered (data intact)"
            else
                fail "post-power-cycle remount data integrity ($MD5D)"
            fi
        else
            fail "post-power-cycle kill-9 remount did not appear"
        fi
    fi
fi

log "6. clean unmount + claim clear no-op + zero PR residue"
run umount "$MNT"
sleep 1
# kill-9'd daemons orphan client heartbeat records; claim clear REFUSES
# while any looks live (one staleness law, TTL 45 s) — prove the refusal,
# wait out the TTL, then prove the no-op.
if ! run "$SQZ" claim clear "sqmeta://$META"; then
    if grep -q "live client registrations" "$OUT"; then
        pass "claim clear refused under TTL-fresh crash-orphaned client records"
    else
        fail "claim clear errored for an unexpected reason"
    fi
    log "waiting out the 45 s client TTL before the no-op check"
    sleep 50
    run "$SQZ" claim clear "sqmeta://$META" || fail "claim clear still refused after TTL"
fi
if grep -q "no writer claim present" "$OUT"; then
    pass "claim clear after clean unmount: no-op (claim deleted at unmount)"
else
    fail "claim clear did not report the no-op"
fi
REG=$(nvme resv-report "$META" --eds -o json 2>/dev/null | jq -r .regctl)
if [ "${REG:-x}" = "0" ]; then
    pass "zero PR residue after clean unmount (regctl=0)"
else
    fail "PR residue after clean unmount (regctl=$REG)"
fi

log "verdict: $FAILS failure(s)"
exit $((FAILS > 0 ? 1 : 0))
