<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>


  <ItemGroup>
    <Reference Include="Garnet.server">
      <HintPath>libs/Garnet.server.dll</HintPath>
    </Reference>
    <Reference Include="Garnet.common">
      <HintPath>libs/Garnet.common.dll</HintPath>
    </Reference>
    <Reference Include="Tsavorite.core">
      <HintPath>libs/Tsavorite.core.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
